{\rtf1\ansi\ansicpg936\cocoartf1187\cocoasubrtf340
{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red38\green38\blue38;\red246\green246\blue246;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl380

\f0\fs26 \cf2 \cb3 safe:        false\
auto:        false\
server:      false\
server_port: 4000\
baseurl:    /blog_github\
url: http://localhost:4000\
\
source:      .\
destination: ./_site\
plugins:     ./_plugins\
\
future:      true\
lsi:         false\
pygments:    false\
markdown:    maruku\
permalink:   date\
\
maruku:\
  use_tex:    false\
  use_divs:   false\
  png_engine: blahtex\
  png_dir:    images/latex\
  png_url:    /images/latex\
\
rdiscount:\
  extensions: []\
\
redcarpet:\
  extensions: []\
\
kramdown:\
  auto_ids: true,\
  footnote_nr: 1\
  entity_output: as_char\
  toc_levels: 1..6\
  use_coderay: false\
  \
  coderay:\
    coderay_wrap: div\
    coderay_line_numbers: inline\
    coderay_line_numbers_start: 1\
    coderay_tab_width: 4\
    coderay_bold_every: 10\
    coderay_css: style\
}